# Generated by Django 5.0.7 on 2024-07-30 12:10

import datetime
import desk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0020_alter_service_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2024, 7, 31), validators=[desk.models.validate_date]),
        ),
    ]
